In [1]:
#The jupyter notebook for Walmart project
# Claire Hu
#

input_file = 'data/train.csv'

with open(input_file, 'r') as f:
    title_str = f.readline()

print(title_str)

"TripType","VisitNumber","Weekday","Upc","ScanCount","DepartmentDescription","FinelineNumber"



In [2]:

title_layout = {}
index = 0
for item in title_str.strip('\n').split(','):
    title_layout[item.strip('"')] = index
    index += 1
print(title_layout)


{'TripType': 0, 'VisitNumber': 1, 'Weekday': 2, 'Upc': 3, 'ScanCount': 4, 'DepartmentDescription': 5, 'FinelineNumber': 6}


In [3]:

DepartmentDescription_set = set()
with open(input_file, 'r') as f:
    for line in f:
        if 'TripType' not in line:
            line_list = line.strip('\n').split(',')
            DepartmentDescription = line_list[title_layout['DepartmentDescription']].strip('"')
            DepartmentDescription_set.add(DepartmentDescription)

In [4]:

print('Total unique DepartmentDescription is:', len(DepartmentDescription_set))

Total unique DepartmentDescription is: 70


In [9]:
Weekday_set = set()
with open(input_file, 'r') as f:
    for line in f:
        if 'TripType' not in line:
            line_list = line.strip('\n').split(',')
            Weekday = line_list[title_layout['Weekday']].strip('"')
            Weekday_set.add(Weekday)

print('Total unique Weekday list is:', Weekday_set, len(Weekday_set))

Total unique Weekday list is: {'Wednesday', 'Tuesday', 'Monday', 'Friday', 'Thursday', 'Sunday', 'Saturday'} 7


In [13]:
import time

In [14]:
transformed_title_list = ["TripType", "VisitNumber", "Weekday", "Upc"]
for field in sorted(DepartmentDescription_set):
    transformed_title_list.append(field)

print('The transformed list is:')
print(transformed_title_list)
        

The transformed list is:
['TripType', 'VisitNumber', 'Weekday', 'Upc', '1-HR PHOTO', 'ACCESSORIES', 'AUTOMOTIVE', 'BAKERY', 'BATH AND SHOWER', 'BEAUTY', 'BEDDING', 'BOOKS AND MAGAZINES', 'BOYS WEAR', 'BRAS & SHAPEWEAR', 'CAMERAS AND SUPPLIES', 'CANDY', 'CELEBRATION', 'COMM BREAD', 'CONCEPT STORES', 'COOK AND DINE', 'DAIRY', 'DSD GROCERY', 'DepartmentDescription', 'ELECTRONICS', 'FABRICS AND CRAFTS', 'FINANCIAL SERVICES', 'FROZEN FOODS', 'FURNITURE', 'GIRLS WEAR', 'GROCERY DRY GOODS', 'HARDWARE', 'HEALTH AND BEAUTY AIDS', 'HOME DECOR', 'HOME MANAGEMENT', 'HORTICULTURE AND ACCESS', 'HOUSEHOLD CHEMICALS/SUPP', 'HOUSEHOLD PAPER GOODS', 'IMPULSE MERCHANDISE', 'INFANT APPAREL', 'INFANT CONSUMABLE HARDLINES', 'JEWELRY AND SUNGLASSES', 'LADIES SOCKS', 'LADIESWEAR', 'LARGE HOUSEHOLD GOODS', 'LAWN AND GARDEN', 'LIQUOR', 'MEAT - FRESH & FROZEN', 'MEDIA AND GAMING', 'MENS WEAR', 'MENSWEAR', 'NULL', 'OFFICE SUPPLIES', 'OPTICAL - FRAMES', 'OPTICAL - LENSES', 'OTHER DEPARTMENTS', 'PAINT AND ACCESSORI

In [18]:
transformed_title_layout = {}
index_t = 0
for item in transformed_title_list:
    transformed_title_layout[item] = index_t
    index_t += 1
print(transformed_title_layout)

{'TripType': 0, 'VisitNumber': 1, 'Weekday': 2, 'Upc': 3, '1-HR PHOTO': 4, 'ACCESSORIES': 5, 'AUTOMOTIVE': 6, 'BAKERY': 7, 'BATH AND SHOWER': 8, 'BEAUTY': 9, 'BEDDING': 10, 'BOOKS AND MAGAZINES': 11, 'BOYS WEAR': 12, 'BRAS & SHAPEWEAR': 13, 'CAMERAS AND SUPPLIES': 14, 'CANDY': 15, 'CELEBRATION': 16, 'COMM BREAD': 17, 'CONCEPT STORES': 18, 'COOK AND DINE': 19, 'DAIRY': 20, 'DSD GROCERY': 21, 'DepartmentDescription': 22, 'ELECTRONICS': 23, 'FABRICS AND CRAFTS': 24, 'FINANCIAL SERVICES': 25, 'FROZEN FOODS': 26, 'FURNITURE': 27, 'GIRLS WEAR': 28, 'GROCERY DRY GOODS': 29, 'HARDWARE': 30, 'HEALTH AND BEAUTY AIDS': 31, 'HOME DECOR': 32, 'HOME MANAGEMENT': 33, 'HORTICULTURE AND ACCESS': 34, 'HOUSEHOLD CHEMICALS/SUPP': 35, 'HOUSEHOLD PAPER GOODS': 36, 'IMPULSE MERCHANDISE': 37, 'INFANT APPAREL': 38, 'INFANT CONSUMABLE HARDLINES': 39, 'JEWELRY AND SUNGLASSES': 40, 'LADIES SOCKS': 41, 'LADIESWEAR': 42, 'LARGE HOUSEHOLD GOODS': 43, 'LAWN AND GARDEN': 44, 'LIQUOR': 45, 'MEAT - FRESH & FROZEN': 46, 

In [62]:
TripType_set = set()
with open(input_file, 'r') as f:
    for line in f:
        if 'TripType' not in line:
            line_list = line.strip('\n').split(',')
            TripType = line_list[title_layout['TripType']].strip('"')
            TripType_set.add(TripType)

print('Total unique TripType list is:', TripType_set, len(TripType_set))

Total unique TripType list is: {'8', '15', '29', '39', '38', '35', '43', '12', '36', '3', '4', '42', '31', '24', '7', '25', '21', '28', '32', '34', '14', '44', '26', '27', '999', '40', '6', '5', '30', '18', '22', '20', '33', '23', '9', '41', '19', '37'} 38


In [65]:
TripType_mapper = {}
mapper_counter = 0
for TripType in sorted(TripType_set):
    TripType_mapper[TripType] = str(mapper_counter)
    mapper_counter += 1

print(TripType_mapper)

{'12': '0', '14': '1', '15': '2', '18': '3', '19': '4', '20': '5', '21': '6', '22': '7', '23': '8', '24': '9', '25': '10', '26': '11', '27': '12', '28': '13', '29': '14', '3': '15', '30': '16', '31': '17', '32': '18', '33': '19', '34': '20', '35': '21', '36': '22', '37': '23', '38': '24', '39': '25', '4': '26', '40': '27', '41': '28', '42': '29', '43': '30', '44': '31', '5': '32', '6': '33', '7': '34', '8': '35', '9': '36', '999': '37'}


In [71]:
output_file = 'data/transformed_train.csv'
counter = 0
with open(input_file, 'r') as f, open(output_file, 'w') as writter:
    for line in f:
        line_list = line.strip('\n').split(',')
        DepartmentDescription = line_list[title_layout['DepartmentDescription']].strip('"')
        
        if counter % 5000 == 0:
            print('Have finished transactions:', counter)
        
        output_str = ''
        if 'TripType' not in line:
            for field in transformed_title_list:
                if field in ["TripType", "VisitNumber", "Weekday", "Upc"]:
                    
                    if field == "Weekday":
                        cur_val_raw = line_list[title_layout[field]].strip('"')
                        cur_val = str(time.strptime(cur_val_raw, "%A").tm_wday)
                    
                    elif field == "TripType":
                        cur_val_raw = line_list[title_layout[field]].strip('"')
                        cur_val = TripType_mapper[cur_val_raw]
                        
                    else:
                        cur_val = line_list[title_layout[field]].strip('"')
                    

                else:
                    DepartmentDescription = line_list[title_layout['DepartmentDescription']].strip('"')
                    if field == DepartmentDescription:
                        cur_val = line_list[title_layout['ScanCount']].strip('"')

                    else:
                        cur_val = '0'
                
                
                if cur_val in [' ', '']:
                    cur_val = '-1'
                output_str += cur_val + ','
        
        else:
            for field in transformed_title_list:
                output_str += field + ','
        
        writter.write(output_str.strip(',') + '\n')
        counter += 1
        
print('Data transformation finished! Total processed records:', counter)
        

Have finished transactions: 0
Have finished transactions: 5000
Have finished transactions: 10000
Have finished transactions: 15000
Have finished transactions: 20000
Have finished transactions: 25000
Have finished transactions: 30000
Have finished transactions: 35000
Have finished transactions: 40000
Have finished transactions: 45000
Have finished transactions: 50000
Have finished transactions: 55000
Have finished transactions: 60000
Have finished transactions: 65000
Have finished transactions: 70000
Have finished transactions: 75000
Have finished transactions: 80000
Have finished transactions: 85000
Have finished transactions: 90000
Have finished transactions: 95000
Have finished transactions: 100000
Have finished transactions: 105000
Have finished transactions: 110000
Have finished transactions: 115000
Have finished transactions: 120000
Have finished transactions: 125000
Have finished transactions: 130000
Have finished transactions: 135000
Have finished transactions: 140000
Have finis

In [72]:
model_ready_file = 'data/transformed_train.csv'
def record_counter():
    counter = 0
    with open(model_ready_file, 'r') as f:
        for line in f:
            if "TripType" not in line:
                counter += 1

    return counter
num_records = record_counter()
print('Total records in file are:', num_records)

Total records in file are: 647054


In [73]:
CUT_RATIO = 0.7

def gen_whole_data_time_series():
    feature_train = []
    target_train = [] 

    feature_test = []
    target_test = []

    start = time.time()

    index = 0
    with open(model_ready_file, 'r') as f:
        for line in f:
            line_list = line.strip('\n').split(',')

            if "TripType" not in line:
                target = int(line_list[transformed_title_layout['TripType']].strip(''))
                feature_list_str = line_list[1:]

                if index % 5000 == 0:
                    print('Have processed number of records:', index, 'time cost:', time.time() - start)
                    start = time.time()

                feature_list_float = []

                for feature_val in feature_list_str:
                    feature_list_float.append(float(feature_val))


                if index <= int(float(num_records) * float(CUT_RATIO)):

                    feature_train.append(feature_list_float)
                    target_train.append(target)

                else:

                    feature_test.append(feature_list_float)
                    target_test.append(target)

                index += 1

    return feature_train, target_train, feature_test, target_test

In [74]:
def over_sample_generator_time_series():
    ros = RandomOverSampler(random_state = random_state)
    feature_train, target_train, feature_test, target_test = gen_whole_data_time_series()
    feature_train_resampled, target_train_resampled = ros.fit_resample(feature_train, target_train)
    return feature_train_resampled, target_train_resampled, feature_test, target_test


def under_sample_generator_time_series():
    rus = RandomUnderSampler(random_state = random_state)
    feature_train, target_train, feature_test, target_test = gen_whole_data_time_series()
    feature_train_resampled, target_train_resampled = rus.fit_resample(feature_train, target_train)
    return feature_train_resampled, target_train_resampled, feature_test, target_test


def SMOTE_sample_generator_time_series():
    sm = SMOTE(random_state=42)
    feature_train, target_train, feature_test, target_test = gen_whole_data_time_series()
    feature_train_resampled, target_train_resampled = sm.fit_resample(feature_train, target_train)
    return feature_train_resampled, target_train_resampled, feature_test, target_test

In [75]:
from imblearn.over_sampling import RandomOverSampler, SMOTE
from imblearn.under_sampling import RandomUnderSampler
random_state = 888

sample_selection_mode = 'time_series'

data_processing_start = time.time()
if sample_selection_mode == 'time_series':
    print('Is using time_series sampling mode...')
    feature_train, target_train, feature_test, target_test = gen_whole_data_time_series()

elif sample_selection_mode == 'time_series_over':
    print('Is using time_series_over mode...')
    feature_train, target_train, feature_test, target_test = over_sample_generator_time_series()

elif sample_selection_mode == 'time_series_under':
    print('Is using time_series_under mode...')
    feature_train, target_train, feature_test, target_test = under_sample_generator_time_series()

else:
    print('Is using time_series_smote mode...')
    feature_train, target_train, feature_test, target_test = SMOTE_sample_generator_time_series()


print('Total time to process all data is:', time.time() - data_processing_start)

Is using time_series sampling mode...
Have processed number of records: 0 time cost: 0.0005991458892822266
Have processed number of records: 5000 time cost: 0.08219194412231445
Have processed number of records: 10000 time cost: 0.08435416221618652
Have processed number of records: 15000 time cost: 0.07744383811950684
Have processed number of records: 20000 time cost: 0.07208585739135742
Have processed number of records: 25000 time cost: 0.07713007926940918
Have processed number of records: 30000 time cost: 0.06986689567565918
Have processed number of records: 35000 time cost: 0.07646322250366211
Have processed number of records: 40000 time cost: 0.07737493515014648
Have processed number of records: 45000 time cost: 0.06839513778686523
Have processed number of records: 50000 time cost: 0.07234406471252441
Have processed number of records: 55000 time cost: 0.06749796867370605
Have processed number of records: 60000 time cost: 0.07337427139282227
Have processed number of records: 65000 ti

Have processed number of records: 600000 time cost: 0.08636593818664551
Have processed number of records: 605000 time cost: 0.08423781394958496
Have processed number of records: 610000 time cost: 0.0748281478881836
Have processed number of records: 615000 time cost: 0.08139324188232422
Have processed number of records: 620000 time cost: 0.08652687072753906
Have processed number of records: 625000 time cost: 0.08004999160766602
Have processed number of records: 630000 time cost: 0.08004379272460938
Have processed number of records: 635000 time cost: 0.07200503349304199
Have processed number of records: 640000 time cost: 0.07936573028564453
Have processed number of records: 645000 time cost: 0.08492064476013184
Total time to process all data is: 12.267173051834106


In [76]:
print('Length of training dataset:', len(feature_train), len(target_train))
print('Length of validation dataset:', len(feature_test), len(target_test))

Length of training dataset: 452938 452938
Length of validation dataset: 194116 194116


In [77]:
num_class_set = set()
for target in target_train:
    num_class_set.add(target)

for target in target_test:
    num_class_set.add(target)

print('Total number or class:', len(num_class_set))
print(sorted(num_class_set))

Total number or class: 38
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37]


In [101]:
param = {
    'max_depth': 5,  # the maximum depth of each tree
    'eta': 0.1,  # the training step for each iteration
    'silent': 1,  # logging mode - quiet
    'objective': 'multi:softprob',  # error evaluation for multiclass training # binary:logistic #multi:softprob
    'scale_pos_weight': 1.0,
    'feature_selector': 'greedy',
    'num_class': len(num_class_set),
    'tree_method': 'hist'
    #'grow_policy': 'lossguide', # depthwise #Controls a way new nodes are added to the tree.
}  # the number of classes that exist in this datset #'num_class': 2

num_round = 100  # the number of training iterations

In [102]:
import datetime, os

DT_format = "%Y%m%d%H%M%S"
work_dir = ''

currentDT = datetime.datetime.now()
model_version = currentDT.strftime(DT_format)

text_model_store_location = work_dir + 'models/'
if not os.path.exists(text_model_store_location):
    os.makedirs(text_model_store_location)
print('Xgboost model will store at:', text_model_store_location)
model_file = text_model_store_location + 'creditcard_xgboost_model_' + model_version + '.md'

Xgboost model will store at: models/


In [103]:


import xgboost as xgb
training_list = transformed_title_list[1:]
def train_model_xgboost(feature_train, target_train):

    dtrain = xgb.DMatrix(feature_train, label=target_train, feature_names=training_list)
    bst = xgb.train(param, dtrain, num_round)
    bst.dump_model(model_file)
    return bst
    
print("Is training the xgboost model...")
start = time.time()
model_bst = train_model_xgboost(feature_train, target_train)
print("Training process finished! Time cost:", time.time() - start)

Is training the xgboost model...
Training process finished! Time cost: 83.1996099948883


In [104]:
def inference_xgboost(bst, feature_test, target_test):
    dtest = xgb.DMatrix(feature_test, label=target_test, feature_names=training_list)
    preds = bst.predict(dtest)
    return preds

print('Is inference the predicted results by using the validation data...')
prediction_result = inference_xgboost(model_bst, feature_test, target_test)
print('Inference finished!')

Is inference the predicted results by using the validation data...
Inference finished!


In [105]:
def print_feature_importance(importance_dict):
    sorted_importance_dict = sorted(importance_dict.items(), key=lambda kv: kv[1], reverse=True)
    print('Credit Card Fraud Detection Feature Importance List:')
    for item in sorted_importance_dict:
        print('Feature Name:', item[0], '\t\t', 'Feature Abs_importance:', item[1])
            
print("Generating the feature importance list...")
importance_dict = model_bst.get_score(importance_type='gain')
print_feature_importance(importance_dict)

Generating the feature importance list...
Credit Card Fraud Detection Feature Importance List:
Feature Name: PHARMACY RX 		 Feature Abs_importance: 405.01018629797915
Feature Name: LADIESWEAR 		 Feature Abs_importance: 317.1432267111415
Feature Name: INFANT CONSUMABLE HARDLINES 		 Feature Abs_importance: 288.4132029604081
Feature Name: FINANCIAL SERVICES 		 Feature Abs_importance: 243.09695698210498
Feature Name: SERVICE DELI 		 Feature Abs_importance: 229.38511061607576
Feature Name: INFANT APPAREL 		 Feature Abs_importance: 227.7977676462042
Feature Name: BEAUTY 		 Feature Abs_importance: 186.09443863618165
Feature Name: MENS WEAR 		 Feature Abs_importance: 178.6209275683727
Feature Name: PHARMACY OTC 		 Feature Abs_importance: 167.28170031432407
Feature Name: PERSONAL CARE 		 Feature Abs_importance: 154.77936096611543
Feature Name: PRODUCE 		 Feature Abs_importance: 147.7360533181869
Feature Name: HORTICULTURE AND ACCESS 		 Feature Abs_importance: 147.42793405246383
Feature Name: BR

In [127]:
from sklearn.metrics import accuracy_score
import numpy as np

#print(len(target_test))
#print(len(prediction_result))

print(prediction_result)
ylabel = np.argmax(prediction_result, axis=1)

yy_list = []
for item in ylabel:
    yy_list.append(item)

accuracy_1 = accuracy_score(np.array(target_test), np.array(yy_list))
accuracy_2 = accuracy_score(np.array(target_test), np.array(yy_list), normalize=True, sample_weight=None)

print('Subset accuracy:', accuracy_2)

[[0.0175093  0.00037399 0.00829174 ... 0.00599242 0.03432281 0.09758631]
 [0.04437825 0.00014111 0.00599576 ... 0.02677289 0.02879497 0.01777044]
 [0.0203148  0.0001539  0.00690398 ... 0.02377742 0.09489341 0.01938147]
 ...
 [0.02044101 0.00013065 0.00620467 ... 0.01976452 0.00484215 0.00723294]
 [0.02446288 0.00015465 0.00492902 ... 0.02552869 0.00699225 0.01599202]
 [0.03645201 0.0001242  0.00499405 ... 0.01808716 0.00323449 0.0050182 ]]
Subset accuracy: 0.3441601928743638
